### ISSUE TITLE
Failed to connect to solana network

### ISSUE THREAD

**Issue by NotHereForTheDong** [Synthetify/synthetify-webapp#432]
![C7545FF3-A961-415A-9D42-254569722A6D](https://github.com/Synthetify/synthetify-webapp/assets/52018850/457ee4d3-cbee-418e-a8af-f6315d406c8b) 
![7EB164EC-627E-4175-836B-14F0CE8C0F97](https://github.com/Synthetify/synthetify-webapp/assets/52018850/55005946-36e4-4132-9a5b-332703fbfcdd)

The rpc seems to be failing for me, I can see via SolScan that the wallet address is still active (https://solscan.io/account/4f1XgkC1dSvvovZ9EU85pY8pwNdJRhqy7jjq188b1DjJ) so it seems to be an issue that isn’t wide spread. I would be happy to try and diagnose this issue further but I am unsure how. I can’t connect either SolFlare or a Phantom to the website. 

Interesting note is it will work on devnet or testnet but not the mainnet. Please advise how this may be resolved if possible. 

Thanks

@NorbertBodziony

**Comment by NorbertBodziony** [comment]
Fixed.

**Comment by NotHereForTheDong** [comment]
Thank you so much! 
![Uploading 871F7292-EE8C-4861-8438-3376FCC4FFD3.jpeg…]()
